### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dunnkers** [zhivkoplias/neural_networks_rug#1]
**Before** preliminary report:

- [x] Report structure @zhivkoplias 
- [x] Save results to a pickle file @dunnkers 
- [x] Auto-generate and save desired graphs in code- with appropriate (axis) labels @zhivkoplias 
- [x] Run setup of the code with high parameters
- [ ] Implement 1 extension @dunnkers 

Thursday:
- [x] Write up report

**After** preliminary report:
1. (refactor code into a python class)
2. Implement another extension
3. Make code even more efficient (combine cell-mapping function with multiprocessing setup?)
